### PACKAGES TO LOAD
###------------------------------------------------------------------#### 
library(ggplot2)  
library(colorspace)
library(tidyr)
library(dplyr)
library(ggthemes)
library(ggpubr)
library(ggrepel)
library(effectsize)
library(ggthemes)


### FILE/FOLDER PATHS
###------------------------------------------------------------------#### 
#path_to_repo <- "/data/"
path_to_repo <- '/Users/tpugh_m04/Documents/Research/PostdoctoralResearch_2020/Projects/PatternRecognitionInGSCs_UsingCV'
#script_path <- '/code'
script_path <- paste0(path_to_repo,'/scripts')
figures_filepath <- paste0(path_to_repo,'/results/')

# general script
source(paste0(script_path,"/sourceData_General_variables_and_functions.R"))
source(paste0(script_path,"/script04b_.R"))


### Supplementary






#TO CHECK THE CONGRUENCY BETWEEN CONFLUENCY GROUPS
hm_col <- sequential_hcl(45, palette='Inferno', rev=T)
hm_col_neg<- sequential_hcl(45, palette='GnBu')

for (hm in 1:3){
  data <- pca_list_medPC_corGSVA[[hm]]
  colours <- data$col
  #names(colours) <- data
  meta <- data[10]
  data.cor <- cor(data[1:9])
  
  pdf(paste0(figures_filepath, 'Sup_fig_S4/S4_C', hm, '.pdf'), width=6.6, height=6)
  pheatmap::pheatmap(data.cor, 
                     #annotation_row = meta, 
                     #annotation_colors = list(cell_type_group=colours), 
                     show_rownames = T, 
                     annotation_legend = F,
                     legend = T,
                     border_color = NA, 
                     cluster_cols =F,
                     cluster_rows = F,
                     fontsize = 21,
                     color = hm_col
  )
  dev.off()
}
























### =====================================================================
###  FIGURES FOR MATERIALS AND METHODS 
### =====================================================================

### SUPPLEMENTARY FIGURE S #
###------------------------------------------------------------------###





# SUPPLEMENTARY FIGURE 1A
###------------------------------------------------------------------###
### Since we are dealing with images with a wide range of plate coverage, we plot the distribution of the total surface area of the image covered by cells growing over them at the time of image capture.
### THis is plotted as a ratio of total surface area of the cell-mask generated by ilastik to the area of the mask image given by mask height * mask width.


#PLOT CELL AREA OCCUPANCY (MEASURED BY AREA OF MASK) AS A FRACTION OF TOTAL AREA AGAINST TIMEPOINT
plist <- list()
for (l in 1:n){
  s <- levels(factor(phase$Sample))[l]
  sample <- phase[phase$Sample==s,]
  plist[[l]] <- ggplot(sample, aes(x=TimePt, y=Area, color=Well)) + 
    scale_color_discrete_qualitative(palette='Dark 2') +
    geom_point(size=0.5) + 
    ylim(0,1) +
    labs(title=s) +
    ylab("Confluency")+
    geom_hline(yintercept=c(0.20,0.40), color='red') +
    geom_hline(yintercept = c(0.75,1.00), color='darkgreen') +
    #scale_y_continuous(breaks=scales::breaks_width(50000)) +
    theme_pubr() + 
    theme(axis.text.x=element_blank(),
          axis.ticks.x =element_blank(),
          axis.text = element_text(size=24),
          plot.title = element_text(size=36),
          legend.position='none')
}
if(dir.exists(paste0(figures_filepath,'Sup_Fig_S1'))==F){
  dir.create(paste0(figures_filepath,'Sup_Fig_S1'))}

pdf(paste0(figures_filepath,'Sup_Fig_S1/S1_A.pdf'), width=25, height=9 )
suppressWarnings(print(ggpubr::ggarrange(plotlist = plist, nrow=2, ncol=8)))
dev.off()






source(paste0(script_path, "/script04_WholeImageAnalysis.R"))


### FIGURES
###------------------------------------------------------------------#### 
# SUPPLEMENTARY FIGURE 9B-C
###------------------------------------------------------------------#### 





### Additional 

g <- list()

for (df in 1:n){
  s <- levels(factor(phaseN$Sample))[df]
  data <- subset(phaseN, Sample==s)
  #meta <- df[1:5]
  #df <- df[6:73] 
  data <- reshape2::melt(data, id=colnames(meta)) %>% mutate(variable=fct_relevel(variable, phase.c.nameOrder[6:73]))
  g[[df]] <- ggplot(data, aes(variable, value, fill=variable)) +
    geom_boxplot(outlier.size =.35) + theme_pander() + 
    scale_color_manual(values=c(col_bold,cols_vivid)) +
    scale_y_continuous(labels=scales::number_format(accuracy=0.01)) +
    theme(axis.line = element_blank(),
          axis.text.x = element_blank(),
          axis.title = element_blank(),
          legend.position = 'none')
  
}
g
### FIGURES
###------------------------------------------------------------------#### 
# SUPPLEMENTARY FIGURE S2A & S3A
###------------------------------------------------------------------#### 
# granularity measurements
phaseN <- phaseN[shorter]
df1 <- phaseN[1:21]
df2 <- phaseN[c(1:5,22:34)]
glist1 <- list()
glist2 <- list()


df1$TimePt <- factor(df1$TimePt, levels =timePt_levels)
for (c in 1:16){
  new_df <- df1[c(3,5,c+5)]
  colnames(new_df) <- c('TimePt','Area','Txt')
  g <- ggplot(new_df, aes(TimePt, Txt, color=Area)) + 
    geom_point(size=0.1, alpha=0.7) +
    theme_classic() +
    scale_color_continuous_sequential(palette='Plasma', rev=F) +
    theme(legend.position = 'none', 
          # axis.line = element_line(color='black'),
          axis.text.x = element_blank(),
          axis.title =element_blank(),
          axis.text.y = element_blank()) +
    labs(title=shorter[c+5])
  
  glist1[[c]] <- g 
}


if(dir.exists(paste0(figures_filepath,'Sup_Fig_S2'))==F){
  dir.create(paste0(figures_filepath,'Sup_Fig_S2'))}

pdf(file = paste0(figures_filepath,'Sup_Fig_S2/S2A.pdf'), width=2.1, height=24)
ggarrange(plotlist=glist1, nrow=16)
dev.off()

df2$TimePt <- factor(df2$TimePt, levels =timePt_levels)

# Haralick/GLCM features
for (c in 1:13){
  new_df <- df2[c(3,5,c+5)]
  colnames(new_df) <- c('TimePt','Area','Txt')
  g <- ggplot(new_df, aes(TimePt, Txt, color=Area)) + 
    geom_point(size=0.1, alpha=0.7) +
    theme_classic() +
    scale_color_continuous_sequential(palette='Plasma', rev=F) +
    theme(legend.position = 'none', 
          # axis.line = element_line(color='black'),
          axis.text.x = element_blank(),
          axis.title =element_blank(),
          axis.text.y = element_blank()) +
    labs(title=shorter[c+21])
  
  glist2[[c]] <- g 
}

if(dir.exists(paste0(figures_filepath,'Sup_Fig_S3'))==F){
  dir.create(paste0(figures_filepath,'Sup_Fig_S3'))}

pdf(file = paste0(figures_filepath,'Sup_Fig_S3/S3A.pdf'), width=2.1, height=24)
ggarrange(plotlist=glist2, nrow=13)
dev.off()
#--------------------------------------------------------------------------------#
#Fig end

### FIGURES METHODS
###------------------------------------------------------------------#### 
# FIGURE METHODS - UNDECIDED
###------------------------------------------------------------------#### 

if(dir.exists(paste0(figures_filepath,'supplementary_methods'))==F){
  dir.create(paste0(figures_filepath,'supplementary_methods'))}

pdf(paste0(figures_filepath,'supplementary_methods/Fig1_A_screeplot.pdf'), width=4.5, height=4.5)
sc
dev.off()

pdf(paste0(figures_filepath,'supplementary_methods/Fig1_B.pdf'), width=4.5, height=4.5)
ggplot(pca_df, aes(PC2, PC1, color=Sample)) +
  geom_jitter(size=1) +
  theme_minimal() +
  scale_color_manual(values=c(cols_vivid, col_bold)) +
  theme(legend.position = 'right', 
        axis.title = element_text(size=12),
        axis.line = element_line(color='black'),
        axis.text.x = element_blank(),
        axis.text.y = element_text(angle=45, size=9)) +
  #geom_text_repel(aes(label=Sample), size=2.5) +
  xlab("PC2") + ylab("PC1")
dev.off()

pdf(paste0(figures_filepath,'supplementary_methods/Fig1_C.pdf'), width=4.5, height=4.5)
ggplot(pca_df, aes(PC2, PC3, color=Sample)) +
  geom_jitter(size=1) +
  theme_minimal() +
  scale_color_manual(values=c(cols_vivid, col_bold)) +
  theme(legend.position = 'right', 
        axis.line = element_line(color='black'),
        axis.text.x = element_blank(),
        axis.text.y = element_text(angle=45, size=9)) +
  #geom_text_repel(aes(label=Sample), size=3) +
  xlab("PC2") + ylab("PC3")
dev.off()


pdf(paste0(figures_filepath,'supplementary_methods/Fig1_D_tp.pdf'), width=4.5, height=4.5)
ggplot(pca_df, aes(PC2, PC1, color=TimePt)) +
  geom_jitter(size=1) +
  theme_minimal() +
  scale_color_discrete_divergingx('TealRose') +
  theme(legend.position = 'none', 
        axis.line = element_line(color='black'),
        axis.text.x = element_blank(),
        axis.text.y = element_text(angle=45, size=9)) +
  #geom_text_repel(aes(label=Sample), size=3) +
  xlab("PC2") + ylab("PC1")
dev.off()


pdf(paste0(figures_filepath,'supplementary_methods/Fig1_E_tp.pdf'), width=4.5, height=4.5)
ggplot(pca_df, aes(PC2, PC3, color=TimePt)) +
  geom_jitter(size=1) +
  theme_minimal() +
  scale_color_discrete_divergingx('TealRose') +
  theme(legend.position = 'none', 
        axis.line = element_line(color='black'),
        axis.text.x = element_blank(),
        axis.text.y = element_text(angle=45, size=9)) +
  #geom_text_repel(aes(label=Sample), size=3) +
  xlab("PC2") + ylab("PC3")
dev.off()
#--------------------------------------------------------------------------------#
#Fig end



#boxplots to show the pixel-area occupancy of each group




### FIGURES
###------------------------------------------------------------------###
# SUPPLEMENTARY FIGURE 4 #
###------------------------------------------------------------------###

if(dir.exists(paste0(figures_filepath,'Sup_Fig_S4'))==F){
  dir.create(paste0(figures_filepath,'Sup_Fig_S4'))}

pdf(file = paste0(figures_filepath,'Sup_Fig_S4/S4_A.pdf'), width=18, height=3)
suppressWarnings(print(ggpubr::ggarrange(plotlist = graphs, nrow=1, ncol=9)))
dev.off()
#--------------------------------------------------------------------------------#
#Fig end


### FIGURES
###------------------------------------------------------------------###
# SUPPLEMENTARY FIGURE 2B
###------------------------------------------------------------------###
#Plotting textural variations across area and time-point after binning into CONFLUENCY GROUPS, showing no or reduced correlation of area/time-pt with textural features
#--- granularity features

final_glist_granularity_combined <- list()

for (d in 1:length(new_df_list)){
  data <- new_df_list[[d]] 
  df1 <- data[1:22]
  #df2 <- data[c(1:5,22:34)]
  
  glist_granularity <- list()
  for (c in 1:16){
    new_df <- df1[c(4,6,c+6)]
    colnames(new_df) <- c('TimePt','Area','Txt')
    g <- ggplot(new_df, aes(TimePt, Txt, color=Area)) + 
      geom_point(size=0.1, alpha=0.7) +
      theme_classic() +
      scale_color_continuous_sequential(palette='Plasma', rev=F) +
      theme(legend.position = 'none', 
            # axis.line = element_line(color='black'),
            axis.text.x = element_blank(),
            axis.title =element_blank(),
            axis.text.y = element_blank()) +
      labs(title=shorter[c+5])
    
    glist_granularity[[c]] <- g 
  }
  final_glist_granularity_combined[[d]] <- ggarrange(plotlist=glist_granularity, nrow=16)
}

tiff(file = paste0(figures_filepath,'Sup_Fig_S2/S2B' ,'.tiff'), width=12, height=24, unit='in', res=300)
ggarrange(plotlist=final_glist_granularity_combined, ncol=9)
dev.off()
#--------------------------------------------------------------------------------#
#Fig end


### FIGURES
###------------------------------------------------------------------###
# SUPPLEMENTARY FIGURE 3B
###------------------------------------------------------------------###
#--- GLCM/Haralick features

final_glist_glcm_combined <- list()
for (d in 1:length(new_df_list)){
  data <- new_df_list[[d]] 
  #df1 <- data[1:21]
  df2 <- data[c(1:6,23:35)]
  
  glist_glcm <- list()
  for (c in 1:13){
    new_df <- df2[c(4,6,c+6)]
    colnames(new_df) <- c('TimePt','Area','Txt')
    g <- ggplot(new_df, aes(TimePt, Txt, color=Area)) + 
      geom_point(size=0.1, alpha=0.7) +
      theme_classic() +
      scale_color_continuous_sequential(palette='Plasma', rev=F) +
      theme(legend.position = 'none', 
            # axis.line = element_line(color='black'),
            axis.text.x = element_blank(),
            axis.title =element_blank(),
            axis.text.y = element_blank()) +
      labs(title=shorter[c+21])
    
    glist_glcm[[c]] <- g 
  }
  final_glist_glcm_combined[[d]] <- ggarrange(plotlist=glist_glcm, nrow=13)
}

tiff(file = paste0(figures_filepath,'Sup_Fig_S3/S3B' ,'.tiff'),res=300, compression='lzw', width=12, height=24, unit='in')
ggarrange(plotlist=final_glist_glcm_combined, ncol=9)
dev.off()
#--------------------------------------------------------------------------------#
#Fig end



